//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace module5_5Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fabrikam2DbContext : DbContext
    {
        public fabrikam2DbContext()
            : base("name=fabrikam2DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<date> dates { get; set; }
        public virtual DbSet<prof_class> prof_class { get; set; }
        public virtual DbSet<professor> professors { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_class> student_class { get; set; }
    
        public virtual ObjectResult<student> findStudent(string fName, string lName, string major)
        {
            var fNameParameter = fName != null ?
                new ObjectParameter("fName", fName) :
                new ObjectParameter("fName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("lName", lName) :
                new ObjectParameter("lName", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<student>("findStudent", fNameParameter, lNameParameter, majorParameter);
        }
    
        public virtual ObjectResult<student> findStudent(string fName, string lName, string major, MergeOption mergeOption)
        {
            var fNameParameter = fName != null ?
                new ObjectParameter("fName", fName) :
                new ObjectParameter("fName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("lName", lName) :
                new ObjectParameter("lName", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<student>("findStudent", mergeOption, fNameParameter, lNameParameter, majorParameter);
        }
    
        public virtual ObjectResult<student> getAllStudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<student>("getAllStudents");
        }
    
        public virtual ObjectResult<student> getAllStudents(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<student>("getAllStudents", mergeOption);
        }
    
        public virtual int insertStudent(string fName, string lName, string major)
        {
            var fNameParameter = fName != null ?
                new ObjectParameter("fName", fName) :
                new ObjectParameter("fName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("lName", lName) :
                new ObjectParameter("lName", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertStudent", fNameParameter, lNameParameter, majorParameter);
        }
    
        public virtual int deleteStudent(string fName, string lName, string major)
        {
            var fNameParameter = fName != null ?
                new ObjectParameter("fName", fName) :
                new ObjectParameter("fName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("lName", lName) :
                new ObjectParameter("lName", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteStudent", fNameParameter, lNameParameter, majorParameter);
        }
    
        public virtual int updateStudent(string fName, string lName, string major)
        {
            var fNameParameter = fName != null ?
                new ObjectParameter("fName", fName) :
                new ObjectParameter("fName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("lName", lName) :
                new ObjectParameter("lName", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateStudent", fNameParameter, lNameParameter, majorParameter);
        }
    }
}
